import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "@/context/authContext"; 
import { GoogleDriveProvider } from "@/context/googleDriveContext";
import { ThemeProvider } from "@/components/themeProvider";

export const metadata: Metadata = {
  title: "AI Kinga",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="h-full">
        <ThemeProvider
          attribute="class"
          defaultTheme="light" 
          enableSystem
          disableTransitionOnChange
        >
          <AuthProvider> 
            <GoogleDriveProvider> 
                {children}
            </GoogleDriveProvider>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}